- name: ansible conditions
  hosts: localhost
  vars:
    age: 20
  tasks:
  - name: print if adult
    ansible.builtin.debug:
      msg: "you are an adult"
    when: age >= 18
  - name: print if minor
    ansible.builtin.debug:
      msg: "you are minor"
    when: age < 18
