- name: ansible conditions
  hosts: localhost
  vars:
    age: 20
  tasks:
  - name: print if adult
    ansible.builtin.debug:
      msg: "you are an adult"
    when: age >= 18
  - name: print if minor
    ansible.builtin.debug:
      msg: "you are minor"
    when: age < 18

- name: condition clear script
  hosts: localhost
  vars:
   name: "ravi"
   age: 20
   devops: true
  tasks:
  - name : check name
    ansible.builtin.debug:
      msg: "my name is ravi"
    when: name == "ravi"
  - name: check age
    ansible.builtin.debug:
      msg: "ravi is major"
    when: age >= 18
  - name: check he learn devops
    ansible.builtin.debug:
      msg: "yes ravi learns devops"
    when: devops == true

    # we use only when in ansible for any condition like above example 

