- name: default ansible
  hosts: localhost
  tasks:
  - name: default ansible
    ansible.builtin.debug:
      msg: "my course is {{course | default('Ansible') }}"

- name : lower case 
  hosts: localhost
  vars:
    greetings: "Good Morning"
  tasks:
  - name: print all all lower case
    ansible.builtin.debug:
      msg: "hello hi {{greetings | lower}}"
- name: upper case
  hosts: localhost
  vars:
    greetings: "Good Morning"
  tasks:      
  - name: print all upper case
    ansible.builtin.debug:
      msg: "hello hi {{greetings | upper}}"

- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [1, 2, 3, 4, 4, 4, 4, 5, 5, 5]
  tasks: 
  - name: remove duplicate numbers 
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"
- name: find out min and max 
  hosts: localhost
  vars:
   ages: [25, 35, 45, 55]
  tasks:
  - name: check min age and max age
    ansible.builtin.debug:
      msg: "min age is {{ ages | min }} and max age is {{ ages | max }}"

- name: convert list of items to dictionary
  hosts: localhost
  list_items:
   - Sivakumar
   - Venu
   - devops
  tasks:
  - name: before convert 
    ansible.builtin.debug:
      msg: "all items {{list_items}}"
  - name: after convert
    ansible.builtin.debug:
      msg: "all items {{ list_items | list2dict}}"



