# Installation of MYSQL
- name: MYSQL Installation
  hosts: [db]
  become: true

  tasks:
  # STEP -1 Update dnf cache
  - name: update dnf cache
    ansible.builtin.dnf:
      update_cache: yes
  # STEP -2 Install MYSQL Server
  - name: install mysql server
    ansible.builtin.dnf:
      name: mysql-server
      state: present
  # STEP -3 Install MYSQL Client    if you use UBUNTU
  # MYSQL CLIENT TASK - not needed in RHEL
  # mysql client tools come with mysql-server package itself
       
  # Step 4 Install python dependencies for mysql
  # needed ansible to talk to mysql
  - name: install python3-PyMySQL
    ansible.builtin.dnf:
      name: python3-PyMySQL
      state: present
  # Step 5 Start and Enable mysql service
  - name: startign and enabling mysql service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes 
  # Step 6 check mysql service status
  - name: check mysql service stated or not
    ansible.builtin.command:
      cmd: systemctl status mysqld
    register: mysql_status

  # Step 7 Print MYSQL status 
  - name: print mysql status
    ansible.builtin.debug:
      msg: " {{ mysql_status.stdout }}"

  # Step 8 Setting up MYSQL Root password 
  - name: set mysql root password
    ansible.builtin.mysql_user:
      name: root
      password: Root@1234
      login_unix_socket: /var/lib/mysql/mysql.sock
      login_user: root
      login_password: ""
      state: present
  # Step 9 create a database 
  - name: creating mysql database
    ansible.builtin.mysql_db:
      name: myappdb
      state: present
      login_user: root
      login_password: "Root@1234"
  # Step 10 create local mysql user
  - name: creating mysql user
    ansible.builtin.mysql_user:
      name: myuser      
      password: "User@1234"
      priv: "myappdb.*:ALL"
      login_user: root
      login_password: Root@1234
      state: present

    


          


