- name : variable preference
  hosts: localhost
  # vars:
  #   wishes: "mng from play variable"
  # vars_files:
  #   - vars.yaml
  # vars_prompt:
  #   - name: wishes
  #     prompt: please enter wishes
  #     private: false
  tasks:
    - name: check preference
      # vars:
      #   wishes: "mornig from task varible"
      ansible.builtin.debug:
        msg: "Hello good {{wishes}}"

#WInners by executing varibales when we given multiple places 
# 1 arguments level
# 2 task level 
# 3 var files level
# 4 prompt level
# 5 Play level
# 6 inventory level
