- name: variables
  hosts: localhost
  vars: #variable declaration
    cource: "kuberneties"
    trainer: "venu"
    duration: "150hrs"
  tasks:
  - name: print infromation
    ansible.builtin.debug:
      msg: "hi, we are learnig {{cource}} from {{trainer}} and the time {{duration}}."


- name: variables
  hosts: [web]
  vars: #Declare vars
  cource: "ansible"
  trainer: "siva"
  duration: "120hrs"
  tasks:
- name: print the infromation
  ansible.builtin.debug:
  msg: "hi, i am learnign {{cource}} from {{trainier}} and timing is {{duration}}."