- name: variables
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks:
  - name: print infromation
    ansible.builtin.debug:
      msg: "hi, we are learnig {{cource}} from {{trainer}} and the time {{duration}}."


- name: variables
  hosts: [web]
  vars_files:
  - vars.yaml
  tasks:
  - name: print the infromation
    ansible.builtin.debug:
      msg: "hi, i am learnign {{cource1}} from {{trainer1}} and timing is {{duration1}}."