- name: data types
  hosts: localhost
  vars:
    course: devops
    subjects: #list
    - linux
    - shell script
    - ansible
    experience: #maps or directory
      devops: 2
      aws: 3
      Docker: 1
    Realproject: true #boolean
  tasks:
    - name: print varibales
      ansible.builtin.debug:
        msg: "hi Iam learnig course{{course}} and subjects are {{subjects}} experience: {{experience}} is it real project {{Realproject}}"