- name: variables
  hosts:  localhost
  vars: #Declare vars
    course: "ansible"
    trainer: "siva"
    duration: "120hrs"
  tasks:
  - name: print information
    vars:
      course: "terraform"
    ansible.builtin.debug:
      msg: "hi i am learning course {{course}} from trainer {{siva}} duration{{duration}}."

  - name: Print information
    ansible.builtin.debug:
      msg: "hi we are learning {{cource}} from trainer {{trainier}} duration{{duration}}."


